# docker-compose --project-directory ./ -f ./services/example-workers/docker-compose.override.yml up
version: "2.1"
services:
  postgresql:
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./services/example-workers/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:r
      - ./services/example-workers/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - 15672:15672
      - 5672:5672
