# RUN BULD ONLY ROOT PROJECT!!!
# docker build -t {{ project_name }} -f ./services/{{ project_name }}/Dockerfile .

FROM python:3.9-bookworm AS builder

WORKDIR /usr/src

COPY ./constraints.txt /usr/src/constraints.txt
COPY ./services/{{ project_name }}/requirements.txt /usr/src/services/{{ project_name }}/requirements.txt
RUN python3 -m pip install -r /usr/src/services/{{ project_name }}/requirements.txt -c /usr/src/constraints.txt

COPY ./scripts/local-support /usr/src/scripts/local-support
RUN python3 -m pip install -e /usr/src/scripts/local-support -c /usr/src/constraints.txt
COPY ./libraries /usr/src/libraries
COPY ./services/{{ project_name }} /usr/src/services/{{ project_name }}
RUN python3 -m local.install --libraries --services

WORKDIR /usr/app

COPY ./scripts/internal /usr/app/scripts

ENTRYPOINT ["uvicorn", "{{ module_name }}.application:app", "--host", "0.0.0.0", "--port", "8080", "--no-access-log"]
